class B
{
	{
		try
		{
			
		}
		catch (Exception ex)
		{
		}
	}
	
}
/*
while using exception or Throwable for a catch both are acting as unchecked.
*/